# Generated by Django 5.0.4 on 2025-08-25 08:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jimok',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('jibun', models.CharField(blank=True, max_length=255, null=True)),
                ('jimok', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=5186)),
            ],
            options={
                'db_table': 'filter"."v_jimok',
                'managed': False,
            },
        ),
    ]
